### ISSUE TITLE
issue "addCommas" 

### ISSUE THREAD

**Issue by mahmudipur** [persian-tools/persian-tools#82]
hey guys!
thanks a lot about this awesome package ,it helped me in my project by converting "numberToWord".

today I wanted to use "addCommas" and I saw a mistake my code : 
html : 
```
<div class="form-group">
<input name="PostPriceCity" id="PostPriceCity" placeholder="هزینه ارسال برای همشهری" class="form-control" />
</div>
```
js : 
```
$('#PostPriceCity').on('keyup', function () {
        var GetValue = $(this).val();
        $(this).val(PersianTools.addCommas(GetValue))
    });
```
my number is for example 5000000 and return is 5,0,0,0,000🤯

I hope you fix this

another problem is using this function. before ,writing just $(this).val(PersianTools.addCommas(GetValue)) returns the resualt but now I have an error in Console and it says : "PersianTools is not defined" so how can I use "addComma" without problem?

your package was added to my project with <script> tag and I can't use npm or anything else ...

**Comment by mediv0** [comment]
hi,
thanks for reporting this bug

about this behavior (  5,0,0,0,000 ):
first, you have to remove commas from your input then passing it into the addCommas function
Also, you have to wait for PersianTools to load then using it otherwise you will get `undefined` error;


for now you can change your code to something like this:
```js
<script type="text/javascript">

    let PersianTools;
    window.addEventListener("load", (event) => {
        PersianTools = this["persian-tools"];
    });

    $("#PostPriceCity").on("keyup", function () {
        var GetValue = $(this).val();
        let val = GetValue.replace(/,/g, "");
        val = PersianTools.addCommas(val);
        $(this).val(val);
    });

</script>

```

**Comment by ali-master** [comment]
Hi @mahmudipur Jan,

Thanks for using the PersianTools in your project, we appreciate it a lot.

The problem is you want to add commas to the amount string whereas it includes commas already when its length goes more than 3, So, But as @mediv0  said before, you need to use the PersianTools' `removeCommas` function before applying the `GetVal` to `addCommas` to ensure that the string is clear of comma keywords and then add commas to the amount string.

Sample:
```javascript
<script type="text/javascript">
    $("#PostPriceCity").on("keyup", function () {
        var GetValue = $(this).val();
        var sanitizedAmount = PersianTools.removeCommas(GetValue);
        var amountWithCommas = PersianTools.addCommas(sanitizedAmount);
        $(this).val(amountWithCommas);
    });
</script>
```

**Comment by mediv0** [comment]
closed due to inactivity
